import { defineConfig } from 'tsup';

// Per ADR-018: ESM-only, dts generated by tsup (handcrafted .d.ts banned),
// sourcemap on, clean before each build, target Node ≥ 22. Uses tsconfig.build.json
// (composite: false) so the dts pipeline doesn't trip on project-reference strictness.
export default defineConfig({
  entry: ['src/index.ts', 'src/abi/index.ts'],
  format: ['esm'],
  dts: { resolve: true },
  sourcemap: true,
  clean: true,
  target: 'node22',
  tsconfig: 'tsconfig.build.json',
});
