import { defineConfig } from 'tsup';

// Per ADR-018: ESM-only, dts generated by tsup, sourcemap on, clean before
// each build, target Node ≥ 22. Story-099 brand tokens — react peer dep is
// optional (tokens.css ships standalone for non-React consumers).
export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: { resolve: true },
  sourcemap: true,
  clean: true,
  target: 'node22',
  tsconfig: 'tsconfig.build.json',
  external: ['react', 'react/jsx-runtime'],
});
